'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {DndContext,DragOverlay,KeyboardSensor,PointerSensor,closestCenter,useDraggable,useDroppable,useSensor,useSensors} from '@dnd-kit/core';
import {SortableContext,arrayMove,sortableKeyboardCoordinates,useSortable,verticalListSortingStrategy} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {ArrowLeft,Check,ChevronDown,ChevronRight,Copy,Download,Eye,EyeOff,GripVertical,History,ImageIcon,Layers3,Lock,Maximize2,Monitor,MoreHorizontal,MousePointer2,Palette,Plus,Redo2,RotateCcw,Save,Settings2,Smartphone,Sparkles,Tablet,Trash2,Undo2,Unlock,Upload,WandSparkles,X} from 'lucide-react';
import {allowedAnimationKeys,allowedStyleKeys,canContain,componentGroups,createComponent,initialTree} from '@/data/componentRegistry';
import './advanced-editor.css';

const clone=v=>JSON.parse(JSON.stringify(v));
const styleFrom=c=>({background:c.styles.background,color:c.styles.color,padding:`${c.styles.padding}px`,margin:`${c.styles.margin}px 0`,gap:`${c.styles.gap}px`,borderRadius:`${c.styles.radius}px`,width:`${c.styles.width}%`,maxWidth:`${c.styles.maxWidth}px`,minHeight:`${c.styles.minHeight}px`,opacity:c.styles.opacity/100,border:`${c.styles.borderWidth}px solid ${c.styles.borderColor}`,boxShadow:`0 ${Math.round(c.styles.shadow/2)}px ${c.styles.shadow*2}px #0005`,filter:`blur(${c.styles.blur}px)`,textAlign:c.styles.align,fontSize:`${c.styles.fontSize}px`,fontWeight:c.styles.fontWeight,gridTemplateColumns:`repeat(${c.styles.columns},minmax(0,1fr))`});

function PaletteItem({type,label,Icon}){const{attributes,listeners,setNodeRef,isDragging}=useDraggable({id:`palette:${type}`,data:{source:'palette',type}});return <button ref={setNodeRef} {...listeners} {...attributes} className={isDragging?'is-dragging':''}><Icon/><span>{label}</span><Plus/></button>}
function SortableLayer({component,depth=0,selected,onSelect,onAction}){const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:component.id,disabled:component.locked});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,paddingLeft:depth*12}} className={`ae-layer ${selected?'selected':''} ${isDragging?'dragging':''}`}><button {...attributes} {...listeners} disabled={component.locked} aria-label={`Move ${component.name}`}><GripVertical/></button><button className="ae-layer-name" onClick={()=>onSelect(component.id)}>{component.children?.length?<ChevronDown/>:<span/>}{component.name}</button><button onClick={()=>onAction('visible',component.id)}>{component.visible?<Eye/>:<EyeOff/>}</button><button onClick={()=>onAction('locked',component.id)}>{component.locked?<Lock/>:<Unlock/>}</button>{component.children?.map(child=><SortableLayer key={child.id} component={child} depth={depth+1} selected={selected===child.id} onSelect={onSelect} onAction={onAction}/>)}</div>}

function Editable({value,onChange,as='p',className=''}){const Tag=as;return <Tag className={className} contentEditable suppressContentEditableWarning onBlur={e=>onChange(e.currentTarget.textContent)}>{value}</Tag>}
function RenderContent({component,updateContent}){
 const c=component.content,u=(key,value)=>updateContent(component.id,key,value);
 switch(component.type){
  case'navbar':return <div className="ae-nav"><Editable as="b" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/></div>;
  case'hero':return <div className="ae-hero"><Editable className="ae-eyebrow" value={c.eyebrow} onChange={v=>u('eyebrow',v)}/><Editable as="h1" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/><Editable as="button" value={c.buttonText} onChange={v=>u('buttonText',v)}/></div>;
  case'heading':return <Editable as="h2" value={c.title} onChange={v=>u('title',v)}/>;
  case'paragraph':return <Editable value={c.text} onChange={v=>u('text',v)}/>;
  case'image':return c.src?<img className="ae-user-image" src={c.src} alt={c.alt||c.title}/>:<div className="ae-image-placeholder"><ImageIcon/><Editable value={c.title} onChange={v=>u('title',v)}/></div>;
  case'button':return <Editable as="button" value={c.buttonText} onChange={v=>u('buttonText',v)}/>;
  case'socials':return <Editable value={c.text} onChange={v=>u('text',v)}/>;
  case'skills':case'projects':case'services':case'gallery':return <div><Editable className="ae-eyebrow" value={c.eyebrow||component.name} onChange={v=>u('eyebrow',v)}/><Editable as="h2" value={c.title} onChange={v=>u('title',v)}/><div className={`ae-items ae-items-${component.type}`}>{(c.items||[]).map((x,i)=><article key={i}><span>0{i+1}</span><Editable as="h3" value={x} onChange={v=>u('items',(c.items||[]).map((item,n)=>n===i?v:item))}/><i/></article>)}</div></div>;
  case'about':case'testimonials':case'contact':return <div><Editable className="ae-eyebrow" value={c.eyebrow||component.type} onChange={v=>u('eyebrow',v)}/><Editable as="h2" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/>{c.buttonText&&<Editable as="button" value={c.buttonText} onChange={v=>u('buttonText',v)}/>}</div>;
  case'divider':return <hr/>;case'spacer':return <div style={{height:Math.max(20,component.styles.minHeight-80)}}/>;
  case'footer':return <div className="ae-footer"><Editable as="h3" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/></div>;
  case'scene3d':return <div className="ae-scene"><div className="ae-orb"/><div><Editable className="ae-eyebrow" value="OPTIONAL 3D" onChange={()=>{}}/><Editable as="h2" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/></div></div>;
  case'animatedBackground':return <div className="ae-mesh"><Editable as="h2" value={c.title} onChange={v=>u('title',v)}/></div>;
  case'video':return <div className="ae-video"><span>▶</span><Editable as="h3" value={c.title} onChange={v=>u('title',v)}/><Editable value={c.text} onChange={v=>u('text',v)}/></div>;
  case'tabs':return <div><Editable as="h2" value={c.title} onChange={v=>u('title',v)}/><div className="ae-tabs">{c.items.map(x=><button key={x}>{x}</button>)}</div></div>;
  default:return <div className={`ae-layout ae-layout-${component.type}`}><small>{component.name} · drop compatible components here</small></div>;
 }
}

function CanvasNode({component,selected,onSelect,onAction,updateContent,children}){
 const{setNodeRef,isOver}=useDroppable({id:`container:${component.id}`,data:{source:'container',componentId:component.id},disabled:!canContain.has(component.type)});
 return <section ref={setNodeRef} data-component={component.type} onClick={e=>{e.stopPropagation();onSelect(component.id)}} className={`ae-node ${selected?'selected':''} ${isOver?'drop-target':''} ${component.visible?'':'hidden-node'} ae-${component.type}`} style={styleFrom(component)}>
  {selected&&<div className="ae-node-toolbar"><span><MousePointer2/> {component.name}</span><button onClick={e=>{e.stopPropagation();onAction('duplicate',component.id)}}><Copy/></button><button onClick={e=>{e.stopPropagation();onAction('delete',component.id)}}><Trash2/></button></div>}
  <RenderContent component={component} updateContent={updateContent}/>
  {children}
 </section>
}

function Canvas({tree,selected,onSelect,onAction,updateContent,device,preview}){
 const{setNodeRef,isOver}=useDroppable({id:'canvas-root',data:{source:'canvas'}});
 const visible=preview?tree.filter(x=>x.visible):tree;
 return <div ref={setNodeRef} className={`ae-page ae-device-${device} ${isOver?'root-over':''} ${preview?'preview-mode':''}`} onClick={()=>onSelect(null)}><SortableContext items={tree.map(x=>x.id)} strategy={verticalListSortingStrategy}>{visible.map(c=><CanvasNode key={c.id} component={c} selected={selected===c.id} onSelect={onSelect} onAction={onAction} updateContent={updateContent}>{c.children?.length>0&&<div className="ae-nested">{c.children.map(child=><CanvasNode key={child.id} component={child} selected={selected===child.id} onSelect={onSelect} onAction={onAction} updateContent={updateContent}/>)}</div>}</CanvasNode>)}</SortableContext>{!tree.length&&<div className="ae-empty"><Plus/><h2>Drop your first component</h2><p>Start with a hero, container, or complete section.</p></div>}</div>
}

function Inspector({component,tab,setTab,onPatch,onAction,aiState,setAiState,runAI,imageState,setImageState,generateImages,uploadImage}){
 if(!component)return <aside className="ae-inspector ae-inspector-empty"><MousePointer2/><h3>Select a component</h3><p>Click anything on the canvas or choose it from Layers.</p></aside>;
 const s=component.styles,c=component.content,a=component.animation;
 return <aside className="ae-inspector"><div className="ae-inspector-title"><div><small>SELECTED COMPONENT</small><input value={component.name} onChange={e=>onPatch({name:e.target.value})}/></div><button><MoreHorizontal/></button></div><div className="ae-inspector-tabs">{[['content','Content'],['design','Design'],['motion','Motion'],['ai','AI'],['image','Image']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='content'&&<div className="ae-controls">{['eyebrow','title','text','buttonText','link','alt'].filter(k=>k in c||['title','text'].includes(k)).map(k=><label key={k}>{k}<textarea value={c[k]||''} onChange={e=>onPatch({content:{...c,[k]:e.target.value}})}/></label>)}<label>Visible<select value={component.visible?'yes':'no'} onChange={e=>onPatch({visible:e.target.value==='yes'})}><option value="yes">Shown</option><option value="no">Hidden</option></select></label></div>}
 {tab==='design'&&<div className="ae-controls"><Control label="Background" type="color" value={s.background} onChange={v=>onPatch({styles:{...s,background:v}})}/><Control label="Text color" type="color" value={s.color} onChange={v=>onPatch({styles:{...s,color:v}})}/>{[['Width','width',20,100,'%'],['Max width','maxWidth',320,1600,'px'],['Min height','minHeight',40,900,'px'],['Padding','padding',0,160,'px'],['Margin','margin',0,120,'px'],['Gap','gap',0,80,'px'],['Radius','radius',0,60,'px'],['Font size','fontSize',10,110,'px'],['Border','borderWidth',0,10,'px'],['Shadow','shadow',0,80,''],['Opacity','opacity',10,100,'%'],['Columns','columns',1,4,'']].map(([label,key,min,max,unit])=><Control key={key} label={label} value={s[key]} min={min} max={max} unit={unit} onChange={v=>onPatch({styles:{...s,[key]:Number(v)}})}/>)}<label>Alignment<select value={s.align} onChange={e=>onPatch({styles:{...s,align:e.target.value}})}><option>left</option><option>center</option><option>right</option></select></label></div>}
 {tab==='motion'&&<div className="ae-controls"><label>Entrance<select value={a.entrance} onChange={e=>onPatch({animation:{...a,entrance:e.target.value}})}><option>none</option><option>fade-up</option><option>scale</option><option>slide-left</option></select></label><label>Hover<select value={a.hover} onChange={e=>onPatch({animation:{...a,hover:e.target.value}})}><option>none</option><option>lift</option><option>glow</option><option>tilt</option></select></label><Control label="Duration" value={a.duration} min={100} max={2000} unit="ms" onChange={v=>onPatch({animation:{...a,duration:Number(v)}})}/><Control label="Delay" value={a.delay} min={0} max={1500} unit="ms" onChange={v=>onPatch({animation:{...a,delay:Number(v)}})}/><label className="ae-check"><input type="checkbox" checked={a.disableMobile} onChange={e=>onPatch({animation:{...a,disableMobile:e.target.checked}})}/> Disable on mobile</label></div>}
 {tab==='ai'&&<div className="ae-ai"><Sparkles/><h3>Redesign this component</h3><p>AI can only change <b>{component.name}</b>. It returns validated settings, never executable code.</p><textarea value={aiState.prompt} onChange={e=>setAiState({...aiState,prompt:e.target.value})} placeholder="Make this component glassmorphism with a smooth hover animation"/><button className="ae-primary" onClick={runAI} disabled={aiState.loading}>{aiState.loading?'Designing…':'Generate redesign'}</button>{aiState.error&&<p className="ae-error">{aiState.error}</p>}{aiState.suggestion&&<div className="ae-suggestion"><div><span>BEFORE</span><span>AFTER</span></div><p>{aiState.suggestion.summary}</p><pre>{JSON.stringify(aiState.suggestion.changes,null,2)}</pre><div><button onClick={()=>setAiState({...aiState,suggestion:null})}>Reject</button><button onClick={()=>onAction('apply-ai',component.id,aiState.suggestion.changes)}>Apply changes</button></div></div>}{component.ai?.lastSuggestion&&<button className="ae-secondary" onClick={()=>onAction('restore-ai',component.id)}>Restore previous design</button>}</div>}
 {tab==='image'&&<div className="ae-media"><ImageIcon/><h3>Image studio</h3><textarea value={imageState.prompt} onChange={e=>setImageState({...imageState,prompt:e.target.value})} placeholder="A futuristic developer workspace with dark blue lighting"/><div className="ae-media-row"><select value={imageState.style} onChange={e=>setImageState({...imageState,style:e.target.value})}>{['Professional','Realistic','3D','Minimal','Futuristic','Illustration','Isometric','Glassmorphism','Cyberpunk','Abstract'].map(x=><option key={x}>{x}</option>)}</select><select value={imageState.aspect} onChange={e=>setImageState({...imageState,aspect:e.target.value})}><option value="landscape">Landscape</option><option value="square">Square</option><option value="portrait">Portrait</option></select></div><button className="ae-primary" onClick={generateImages} disabled={imageState.loading}>{imageState.loading?'Generating four options…':'Generate 4 images'}</button><label className="ae-upload"><Upload/> Upload JPG, PNG, WebP or AVIF<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={uploadImage}/></label>{imageState.error&&<p className="ae-error">{imageState.error}</p>}<div className="ae-image-grid">{imageState.images.map((src,i)=><article key={src.slice(-40)+i}><img src={src} alt={`Generated variation ${i+1}`}/><div><button onClick={()=>onPatch({content:{...c,src,alt:imageState.prompt||'Portfolio image'}})}>Use</button><a href={src} download={`portfolio-image-${i+1}.png`}><Download/></a></div></article>)}</div></div>}
 </aside>
}
function Control({label,value,onChange,min=0,max=100,type='range',unit=''}){return <label>{label}<span>{value}{unit}</span><input type={type} value={value} min={min} max={max} onChange={e=>onChange(e.target.value)}/></label>}

export default function AdvancedEditor(){
 const[tree,setTree]=useState([]),[selected,setSelected]=useState(null),[activeDrag,setActiveDrag]=useState(null),[device,setDevice]=useState('desktop'),[leftTab,setLeftTab]=useState('components'),[rightTab,setRightTab]=useState('design'),[preview,setPreview]=useState(false),[history,setHistory]=useState({past:[],future:[]}),[versions,setVersions]=useState([]),[showVersions,setShowVersions]=useState(false),[notice,setNotice]=useState(''),[globalAI,setGlobalAI]=useState({prompt:'',loading:false,error:''}),[aiState,setAiState]=useState({prompt:'',loading:false,suggestion:null,error:''}),[imageState,setImageState]=useState({prompt:'',style:'Professional',aspect:'landscape',loading:false,images:[],error:''});
 const initialized=useRef(false),sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 useEffect(()=>{const saved=localStorage.getItem('portfolio-studio-tree');const savedVersions=localStorage.getItem('portfolio-studio-versions');setTree(saved?JSON.parse(saved):initialTree());setVersions(savedVersions?JSON.parse(savedVersions):[]);initialized.current=true},[]);
 useEffect(()=>{if(initialized.current&&tree.length)localStorage.setItem('portfolio-studio-tree',JSON.stringify(tree))},[tree]);
 const commit=useCallback(next=>{setTree(current=>{const value=typeof next==='function'?next(current):next;setHistory(h=>({past:[...h.past.slice(-49),clone(current)],future:[]}));return value})},[]);
 const find=useCallback((items,id)=>{for(const c of items){if(c.id===id)return c;const nested=find(c.children||[],id);if(nested)return nested}return null},[]);
 const selectedComponent=find(tree,selected);
 const mapTree=(items,id,fn)=>items.map(c=>c.id===id?fn(c):{...c,children:mapTree(c.children||[],id,fn)});
 const removeTree=(items,id)=>items.filter(c=>c.id!==id).map(c=>({...c,children:removeTree(c.children||[],id)}));
 const patchSelected=patch=>{if(!selected)return;commit(items=>mapTree(items,selected,c=>({...c,...patch,updatedAt:new Date().toISOString()})))};
 const updateContent=(id,key,value)=>commit(items=>mapTree(items,id,c=>({...c,content:{...c.content,[key]:value},updatedAt:new Date().toISOString()})));
 const action=(type,id,payload)=>{
  const target=find(tree,id);if(!target)return;
  if(type==='delete'){commit(items=>removeTree(items,id));if(selected===id)setSelected(null)}
  if(type==='duplicate'){const copy=clone(target);copy.id=crypto.randomUUID();copy.name=`${copy.name} copy`;copy.createdAt=new Date().toISOString();const index=tree.findIndex(x=>x.id===id);commit([...tree.slice(0,index+1),copy,...tree.slice(index+1)]);setSelected(copy.id)}
  if(type==='visible'||type==='locked')commit(items=>mapTree(items,id,c=>({...c,[type]:!c[type]})));
  if(type==='apply-ai'){commit(items=>mapTree(items,id,c=>({...c,styles:{...c.styles,...payload.styles},content:{...c.content,...payload.content},responsive:{...c.responsive,...payload.responsive},animation:{...c.animation,...payload.animation},ai:{prompt:aiState.prompt,lastSuggestion:{before:{styles:c.styles,content:c.content,responsive:c.responsive,animation:c.animation},after:payload}}})));setAiState({...aiState,suggestion:null});setNotice('AI redesign applied to the selected component.')}
  if(type==='restore-ai'&&target.ai?.lastSuggestion){const before=target.ai.lastSuggestion.before;commit(items=>mapTree(items,id,c=>({...c,...before,ai:{...c.ai,lastSuggestion:null}})));setNotice('Previous component design restored.')}
 };
 const undo=()=>setHistory(h=>{if(!h.past.length)return h;const previous=h.past.at(-1);setTree(current=>{h.future.unshift(clone(current));return previous});return{past:h.past.slice(0,-1),future:h.future}});
 const redo=()=>setHistory(h=>{if(!h.future.length)return h;const next=h.future[0];setTree(current=>{h.past.push(clone(current));return next});return{past:h.past,future:h.future.slice(1)}});
 const onDragEnd=({active,over})=>{setActiveDrag(null);if(!over)return;const source=active.data.current;if(source?.source==='palette'){const component=createComponent(source.type);if(String(over.id).startsWith('container:')){const parentId=String(over.id).split(':')[1];if(canContain.has(find(tree,parentId)?.type)){component.parentId=parentId;commit(items=>mapTree(items,parentId,c=>({...c,children:[...(c.children||[]),component]})));setSelected(component.id)}}else{commit([...tree,component]);setSelected(component.id)}return}const old=tree.findIndex(x=>x.id===active.id),next=tree.findIndex(x=>x.id===over.id);if(old>=0&&next>=0&&old!==next)commit(arrayMove(tree,old,next))};
 const saveVersion=()=>{const name=prompt('Name this version','Design checkpoint');if(!name)return;const version={id:crypto.randomUUID(),name,createdAt:new Date().toISOString(),tree:clone(tree)};const next=[version,...versions].slice(0,20);setVersions(next);localStorage.setItem('portfolio-studio-versions',JSON.stringify(next));setNotice(`Version “${name}” saved.`)};
 const runAI=async()=>{if(!aiState.prompt.trim())return setAiState({...aiState,error:'Describe the redesign you want.'});setAiState({...aiState,loading:true,error:'',suggestion:null});try{const r=await fetch('/api/builder/component-design',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:aiState.prompt,component:{type:selectedComponent.type,content:selectedComponent.content,styles:selectedComponent.styles,responsive:selectedComponent.responsive,animation:selectedComponent.animation}})}),j=await r.json();if(!r.ok)throw new Error(j.error);setAiState(s=>({...s,loading:false,suggestion:j,error:''}))}catch(e){setAiState(s=>({...s,loading:false,error:e.message||'AI redesign failed.'}))}};
 const generateImages=async()=>{if(!imageState.prompt.trim())return setImageState({...imageState,error:'Describe the image you need.'});setImageState({...imageState,loading:true,error:'',images:[]});try{const r=await fetch('/api/builder/images',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:imageState.prompt,style:imageState.style,aspect:imageState.aspect,count:4})}),j=await r.json();if(!r.ok)throw new Error(j.error);setImageState(s=>({...s,loading:false,images:j.images,error:''}))}catch(e){setImageState(s=>({...s,loading:false,error:e.message||'Image generation failed.'}))}};
 const uploadImage=e=>{const file=e.target.files?.[0];if(!file)return;const allowed=['image/jpeg','image/png','image/webp','image/avif'];if(!allowed.includes(file.type)||file.size>5*1024*1024)return setImageState({...imageState,error:'Use a JPG, PNG, WebP or AVIF under 5 MB.'});const reader=new FileReader();reader.onload=()=>{setImageState(s=>({...s,images:[reader.result,...s.images],error:''}));if(selectedComponent)patchSelected({content:{...selectedComponent.content,src:reader.result,alt:file.name}})};reader.readAsDataURL(file)};
 const generateSite=async()=>{if(!globalAI.prompt.trim())return setGlobalAI({...globalAI,error:'Describe the portfolio you want.'});setGlobalAI({...globalAI,loading:true,error:''});try{const r=await fetch('/api/builder/site-design',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:globalAI.prompt})}),j=await r.json();if(!r.ok)throw new Error(j.error);const generated=j.components.map((item,index)=>{const component=createComponent(item.type);if(item.title)component.content.title=item.title;component.styles={...component.styles,background:index%2?j.theme.background:'#0b1728',color:j.theme.color,borderColor:`${j.theme.accent}55`};return component});commit(generated);setSelected(generated[0]?.id||null);setGlobalAI(s=>({...s,loading:false,error:''}));setNotice(j.summary)}catch(e){setGlobalAI(s=>({...s,loading:false,error:e.message||'Website generation failed.'}))}};
 const exportJSON=()=>{const blob=new Blob([JSON.stringify({version:1,tree},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='portfolio-component-tree.json';a.click();URL.revokeObjectURL(url);setNotice('Validated component tree downloaded.')};
 return <DndContext id="portfolio-editor-dnd" sensors={sensors} collisionDetection={closestCenter} onDragStart={({active})=>setActiveDrag(active)} onDragEnd={onDragEnd} onDragCancel={()=>setActiveDrag(null)}><div className="ae-shell"><header className="ae-top"><a href="/builder"><ArrowLeft/> Templates</a><div className="ae-project"><i/>Untitled portfolio <ChevronDown/></div><div className="ae-history-actions"><button onClick={undo} disabled={!history.past.length} title="Undo"><Undo2/></button><button onClick={redo} disabled={!history.future.length} title="Redo"><Redo2/></button><button onClick={saveVersion}><Save/> Save version</button><button onClick={()=>setShowVersions(!showVersions)}><History/> History</button></div><div className="ae-devices">{[['desktop',Monitor],['tablet',Tablet],['mobile',Smartphone]].map(([id,I])=><button className={device===id?'active':''} key={id} onClick={()=>setDevice(id)}><I/></button>)}</div><div className="ae-actions"><button onClick={()=>setPreview(!preview)}><Eye/> {preview?'Edit':'Preview'}</button><button onClick={exportJSON}><Download/> Export tree</button></div></header><main className={`ae-main ${preview?'is-preview':''}`}>
 <aside className="ae-library-panel"><div className="ae-left-tabs"><button className={leftTab==='components'?'active':''} onClick={()=>setLeftTab('components')}><Plus/> Add</button><button className={leftTab==='layers'?'active':''} onClick={()=>setLeftTab('layers')}><Layers3/> Layers</button></div>{leftTab==='components'?<div className="ae-component-list"><div className="ae-global-ai"><WandSparkles/><b>Build from one prompt</b><p>Create a complete editable site structure.</p><textarea value={globalAI.prompt} onChange={e=>setGlobalAI({...globalAI,prompt:e.target.value})} placeholder="A futuristic full-stack developer portfolio with a 3D hero and bento projects"/><button onClick={generateSite} disabled={globalAI.loading}>{globalAI.loading?'Generating…':'Generate structure'}</button>{globalAI.error&&<small>{globalAI.error}</small>}</div>{componentGroups.map(g=><div key={g.name}><h3>{g.name}</h3><div>{g.items.map(([type,label,Icon])=><PaletteItem key={type} type={type} label={label} Icon={Icon}/>)}</div></div>)}</div>:<div className="ae-layers"><div className="ae-layer-root"><b>Page</b><span>{tree.length} sections</span></div><SortableContext items={tree.map(x=>x.id)} strategy={verticalListSortingStrategy}>{tree.map(c=><SortableLayer key={c.id} component={c} selected={selected} onSelect={setSelected} onAction={action}/>)}</SortableContext></div>}</aside>
 <section className="ae-stage"><div className="ae-stage-label"><span>{device} · {device==='desktop'?'1440':device==='tablet'?'768':'390'}px</span><span>Drag components onto the canvas · Click text to edit</span></div><Canvas tree={tree} selected={selected} onSelect={setSelected} onAction={action} updateContent={updateContent} device={device} preview={preview}/></section><Inspector component={selectedComponent} tab={rightTab} setTab={setRightTab} onPatch={patchSelected} onAction={action} aiState={aiState} setAiState={setAiState} runAI={runAI} imageState={imageState} setImageState={setImageState} generateImages={generateImages} uploadImage={uploadImage}/></main>
 {showVersions&&<div className="ae-versions"><div><h2>Version history</h2><button onClick={()=>setShowVersions(false)}><X/></button></div>{versions.length?versions.map(v=><article key={v.id}><div><b>{v.name}</b><span>{new Date(v.createdAt).toLocaleString()}</span></div><button onClick={()=>{commit(clone(v.tree));setShowVersions(false);setNotice(`Restored “${v.name}”.`)}}><RotateCcw/> Restore</button></article>):<p>No named versions yet. Automatic draft saving is active.</p>}</div>}
 {notice&&<div className="ae-notice"><Check/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}<DragOverlay>{activeDrag?<div className="ae-drag-overlay"><GripVertical/> Move component</div>:null}</DragOverlay></div></DndContext>
}
