'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';
import {ArrowLeft,ArrowRight,Check,ChevronDown,Download,Eye,Laptop,LayoutGrid,LoaderCircle,Monitor,Plus,Search,Smartphone,Sparkles,Tablet,WandSparkles,X} from 'lucide-react';
import {builderTemplates,initialPortfolio} from '@/data/builderTemplates';
import './builder.css';
const steps=['Template','Content','Design','Preview'];
const examples=['Modern developer · dark','Minimal fresher portfolio','Blue glassmorphism'];

function TemplateCard({template,selected,onSelect}){return <article className={`pb-template-card ${selected?'selected':''}`}><div className="pb-template-art pb-template-preview"><Image src={template.previewImage} alt={template.previewAlt} fill sizes="(max-width: 760px) 100vw, (max-width: 1100px) 50vw, 33vw"/>{template.is3D&&<small>3D</small>}</div><div className="pb-template-meta"><div><h3>{template.name}</h3><p>{template.category}</p></div><span>FREE</span></div><div className="pb-chips">{template.features.map(x=><span key={x}>{x}</span>)}</div><button onClick={()=>onSelect(template)}>{selected?<><Check/> Selected</>:<>Use template <ArrowRight/></>}</button></article>}
function Preview({data,design,template,device}){return <div className={`pb-device pb-${device}`}><div className={`pb-site layout-${template.layout} is-${design.theme}`} style={{'--accent':design.primary,'--radius':`${design.radius}px`,'--space':`${design.spacing}px`,fontFamily:design.font}}><nav><b>{data.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</b><div><span>About</span><span>Work</span><span>Contact</span></div></nav><header><p className="eyebrow">PORTFOLIO · {new Date().getFullYear()}</p><h1>{data.name}</h1><h2>{data.title}</h2><p>{data.intro}</p><button>Explore my work <ArrowRight/></button></header><section className="pb-preview-about"><small>ABOUT</small><p>{data.about}</p></section><section className="pb-preview-skills">{data.skills.map(x=><span key={x}>{x}</span>)}</section><section className="pb-preview-projects">{data.projects.map((p,i)=><article key={p.id}><div><span>0{i+1}</span><i/></div><h3>{p.title}</h3><p>{p.description}</p><small>{p.tech}</small></article>)}</section><footer><h2>Let’s make something useful.</h2><a>{data.email}</a></footer></div></div>}

export default function BuilderClient(){
 const[step,setStep]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[template,setTemplate]=useState(builderTemplates[0]),[data,setData]=useState(initialPortfolio),[design,setDesign]=useState({primary:'#6ea8ff',theme:'dark',font:'Manrope, sans-serif',radius:18,spacing:72}),[device,setDevice]=useState('desktop'),[aiPrompt,setAiPrompt]=useState(''),[aiField,setAiField]=useState('intro'),[aiBusy,setAiBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const draft=localStorage.getItem('portfolio-studio-draft');if(draft)try{const p=JSON.parse(draft);setData(p.data||initialPortfolio);setDesign(p.design||design);setTemplate(builderTemplates.find(x=>x.id===p.templateId)||builderTemplates[0])}catch{}},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{localStorage.setItem('portfolio-studio-draft',JSON.stringify({data,design,templateId:template.id}))},[data,design,template]);
 const filtered=useMemo(()=>builderTemplates.filter(t=>(filter==='All'||(filter==='3D'?t.is3D:t.theme===filter.toLowerCase()||t.category.toLowerCase().includes(filter.toLowerCase())))&&`${t.name} ${t.category} ${t.features.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);
 const update=(key,value)=>setData(d=>({...d,[key]:value}));const selectTemplate=t=>{setTemplate(t);setDesign(d=>({...d,primary:t.accent,theme:t.theme}))};
 const runAI=async(mode='improve')=>{const source=aiPrompt||data[aiField];if(!source?.trim())return setNotice('Add source information first. AI never invents credentials or experience.');setAiBusy(true);setNotice('');try{const response=await fetch('/api/builder/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,field:aiField,source})});const result=await response.json();if(!response.ok)throw new Error(result.error);update(aiField,result.text);setNotice('AI suggestion applied. You can edit or regenerate it.')}catch(error){setNotice(error.message||'AI is unavailable right now.')}finally{setAiBusy(false)}};
 const addProject=()=>update('projects',[...data.projects,{id:crypto.randomUUID(),title:'New project',description:'Describe the problem and outcome.',tech:'Technology stack'}]);
 const updateProject=(id,key,value)=>update('projects',data.projects.map(p=>p.id===id?{...p,[key]:value}:p));
 const download=()=>{const safe=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${safe(data.name)} — ${safe(data.title)}</title><style>body{margin:0;background:${design.theme==='dark'?'#08111f':'#f8fafc'};color:${design.theme==='dark'?'#f8fafc':'#111827'};font:16px/1.6 system-ui}main{max-width:1100px;margin:auto;padding:10vw 6vw}h1{font-size:clamp(4rem,12vw,9rem);line-height:.85;margin:.4em 0;color:${design.primary}}h2{font-size:2rem}.projects{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px}.card{padding:28px;border:1px solid #64748b55;border-radius:${design.radius}px}a{color:${design.primary}}</style></head><body><main><small>PORTFOLIO</small><h1>${safe(data.name)}</h1><h2>${safe(data.title)}</h2><p>${safe(data.intro)}</p><hr><h2>About</h2><p>${safe(data.about)}</p><h2>Selected work</h2><div class="projects">${data.projects.map(p=>`<article class="card"><h3>${safe(p.title)}</h3><p>${safe(p.description)}</p><small>${safe(p.tech)}</small></article>`).join('')}</div><h2>Let’s talk</h2><a href="mailto:${safe(data.email)}">${safe(data.email)}</a></main></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download=`${data.name.toLowerCase().replace(/\W+/g,'-')||'portfolio'}.html`;a.click();URL.revokeObjectURL(url);setNotice('Your portable portfolio HTML was downloaded.')};
 return <div className="pb-shell"><header className="pb-topbar"><a href="/" className="pb-back"><ArrowLeft/> Raj Patel</a><div className="pb-brand"><WandSparkles/><div><b>Portfolio Studio</b><span>AI website builder</span></div></div><div className="pb-top-actions"><span className="pb-saved"><Check/> Draft saved</span><a className="pb-editor-launch" href="/builder/editor"><LayoutGrid/> Visual Editor</a><button onClick={download}><Download/> Export</button></div></header><div className="pb-progress">{steps.map((s,i)=><button key={s} className={step===i?'active':step>i?'done':''} onClick={()=>setStep(i)}><span>{step>i?<Check/>:i+1}</span>{s}</button>)}</div>
 {step===0&&<main className="pb-library"><div className="pb-library-head"><div><p>START WITH A DIRECTION</p><h1>Pick a layout with a point of view.</h1><span>20 distinct foundations. Your content stays intact when you switch.</span></div><div className="pb-prompt-card"><Sparkles/><label>Describe your ideal portfolio</label><textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Create a modern developer portfolio with dark theme and smooth animations"/><div>{examples.map(x=><button key={x} onClick={()=>setAiPrompt(`Create a ${x}`)}>{x}</button>)}</div><button className="pb-ai-button" onClick={()=>runAI('recommend')} disabled={aiBusy}>{aiBusy?<LoaderCircle className="spin"/>:<Sparkles/>} Recommend a direction</button></div></div><div className="pb-tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search templates"/></label><div>{['All','Dark','Light','3D','Developer','Designer','Student'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="pb-template-grid">{filtered.map(t=><TemplateCard key={t.id} template={t} selected={template.id===t.id} onSelect={selectTemplate}/>)}</div></main>}
 {step>0&&<main className="pb-workspace"><aside className="pb-editor">{step===1&&<><PanelHead kicker="YOUR STORY" title="Content" text="Only use real information. AI improves what you provide."/>{['name','title','intro','about','email','location'].map(key=><label key={key}>{key==='intro'?'Short introduction':key[0].toUpperCase()+key.slice(1)}{key==='about'?<textarea value={data[key]} onChange={e=>update(key,e.target.value)}/>:<input value={data[key]} onChange={e=>update(key,e.target.value)}/>}</label>)}<label>Skills<input value={data.skills.join(', ')} onChange={e=>update('skills',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/><small>Separate with commas</small></label><div className="pb-project-head"><h3>Projects</h3><button onClick={addProject}><Plus/> Add</button></div>{data.projects.map((p,i)=><div className="pb-project-edit" key={p.id}><span>PROJECT 0{i+1}</span><button aria-label="Remove project" onClick={()=>update('projects',data.projects.filter(x=>x.id!==p.id))}><X/></button><input value={p.title} onChange={e=>updateProject(p.id,'title',e.target.value)}/><textarea value={p.description} onChange={e=>updateProject(p.id,'description',e.target.value)}/><input value={p.tech} onChange={e=>updateProject(p.id,'tech',e.target.value)}/></div>)}<div className="pb-ai-panel"><Sparkles/><h3>AI writing partner</h3><select value={aiField} onChange={e=>setAiField(e.target.value)}><option value="intro">Introduction</option><option value="about">About me</option></select><div><button onClick={()=>runAI('professional')}>Professional</button><button onClick={()=>runAI('shorter')}>Shorter</button><button onClick={()=>runAI('simple')}>Simple English</button></div><button className="pb-ai-button" onClick={()=>runAI()} disabled={aiBusy}>{aiBusy?<LoaderCircle className="spin"/>:<Sparkles/>} Improve with AI</button></div></>}
 {step===2&&<><PanelHead kicker="MAKE IT YOURS" title="Design" text="Changes appear instantly in the preview."/><label>Primary color<div className="pb-color"><input type="color" value={design.primary} onChange={e=>setDesign({...design,primary:e.target.value})}/><input value={design.primary} onChange={e=>setDesign({...design,primary:e.target.value})}/></div></label><label>Theme<select value={design.theme} onChange={e=>setDesign({...design,theme:e.target.value})}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Font<select value={design.font} onChange={e=>setDesign({...design,font:e.target.value})}><option>Manrope, sans-serif</option><option>Georgia, serif</option><option>monospace</option></select></label><label>Card radius <b>{design.radius}px</b><input type="range" min="0" max="36" value={design.radius} onChange={e=>setDesign({...design,radius:Number(e.target.value)})}/></label><label>Section spacing <b>{design.spacing}px</b><input type="range" min="40" max="120" value={design.spacing} onChange={e=>setDesign({...design,spacing:Number(e.target.value)})}/></label><div className="pb-template-switch"><h3>Template</h3><button onClick={()=>setStep(0)}><LayoutGrid/> {template.name}<ChevronDown/></button></div></>}
 {step===3&&<><PanelHead kicker="READY TO SHARE" title="Preview & export" text="Check every screen size, then download a clean portable site."/><div className="pb-checklist">{['Real content reviewed','Mobile layout checked','Email address confirmed','Motion preferences supported'].map(x=><p key={x}><Check/> {x}</p>)}</div><button className="pb-publish" onClick={download}><Download/> Download portfolio HTML</button><p className="pb-auth-note">Cloud publishing and account saves require production authentication and hosting credentials. This draft remains saved on your device.</p></>}</aside><section className="pb-canvas"><div className="pb-previewbar"><div>{[['mobile',Smartphone],['tablet',Tablet],['laptop',Laptop],['desktop',Monitor]].map(([x,I])=><button key={x} className={device===x?'active':''} onClick={()=>setDevice(x)} aria-label={`${x} preview`}><I/></button>)}</div><span><Eye/> Live preview</span></div><Preview data={data} design={design} template={template} device={device}/></section></main>}
 {notice&&<div className="pb-toast" role="status">{notice}<button onClick={()=>setNotice('')}><X/></button></div>}<div className="pb-bottom"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button><span>Step {step+1} of {steps.length}</span>{step<3?<button className="primary" onClick={()=>setStep(s=>s+1)}>Continue <ArrowRight/></button>:<button className="primary" onClick={download}>Export <Download/></button>}</div></div>
}
function PanelHead({kicker,title,text}){return <div className="pb-panel-head"><p>{kicker}</p><h2>{title}</h2><span>{text}</span></div>}
