'use client';
import Image from 'next/image'; import Link from 'next/link'; import { motion } from 'framer-motion'; import { ArrowDown, ArrowRight, BriefcaseBusiness, Eye, Handshake, Workflow, PhoneCall, School, ShieldCheck, Gauge, Folder, X, Sparkles } from 'lucide-react'; import { useState } from 'react'; import { projects,journey,skillGroups } from '@/data/portfolio'; import ScrollJourney from '@/components/scroll-journey/ScrollJourney';
const paths=[['I want to hire you','Experience, core strengths, resume & availability',BriefcaseBusiness,'#contact'],['I want to see your work','Selected products, decisions & outcomes',Eye,'#work'],['I want to collaborate','Ideas, interests & ways to build together',Handshake,'#explore'],['I want to understand your process','How I plan, build, test & launch',Workflow,'#thinking']];
export default function HomeClient(){const [folder,setFolder]=useState(null);return <>
<ScrollJourney/>
<section className="prompt-generator-callout section"><div><p className="kicker">NEW · FREE WEBSITE PLANNING TOOL</p><h2>Turn a rough idea into a build-ready prompt.</h2><p>Choose the website type, language, stack, pages, design, integrations and deployment. Get a professional prompt ready for ChatGPT, Claude, Cursor, Gemini, Bolt, Lovable or Replit.</p><div className="hero-actions"><Link className="button light" href="/website-prompt-generator">Generate Website Prompt <ArrowRight/></Link><Link className="button ghost" href="/website-prompt-generator">Create Modern Website With AI <Sparkles/></Link><Link className="button ghost" href="/website-prompt-generator">Explore Website Prompts <Eye/></Link></div></div><div className="prompt-flow"><span>01</span><p>Choose your website</p><span>02</span><p>Shape the stack</p><span>03</span><p>Copy the brief</p></div></section>
<section className="builder-callout section"><div><p className="kicker">NEW · PORTFOLIO STUDIO</p><h2>Your work deserves a site with a point of view.</h2><p>Choose from 20 distinct templates, shape your story with AI, customize every detail, and export a responsive portfolio—no resume required.</p><div className="hero-actions"><Link className="button light" href="/builder">Create Your Portfolio Free <ArrowRight/></Link><Link className="button ghost" href="/builder">Build With AI <Sparkles/></Link><Link className="button ghost" href="/builder">Explore Templates <Eye/></Link></div></div><div className="builder-callout-orbit"><span>20</span><p>production-ready directions</p><i>AI</i><i>3D</i><i>FAST</i></div></section>
<section className="hero"><Image src="/images/hero-workspace.png" alt="Dark architectural developer workspace with floating interface panels" fill priority sizes="100vw" className="hero-image"/><div className="hero-shade"/><div className="hero-copy"><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="kicker">FULL-STACK DEVELOPER · PRODUCT THINKER</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.1}}>I build digital products that solve <em>real business problems.</em></motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}} className="intro">Modern web applications, mobile experiences, and backend systems — shaped around the people who rely on them.</motion.p><div className="hero-actions"><Link className="button light" href="#work">Explore my work <ArrowRight/></Link><Link className="button ghost" href="#paths">Choose your path <ArrowDown/></Link></div></div><div className="hero-note"><span>BASED IN INDIA</span><span>BUILDING FOR THE WEB + MOBILE</span></div></section>
<section id="paths" className="section paths"><div className="section-head"><p className="kicker">01 · CHOOSE YOUR PATH</p><h2>What brought you here?</h2><p>Skip the generic tour. Start with what matters to you.</p></div><div className="path-grid">{paths.map(([a,b,I,h],i)=><Link href={h} className="path-card" key={a}><span>0{i+1}</span><I/><h3>{a}</h3><p>{b}</p><ArrowRight className="path-arrow"/></Link>)}</div></section>
<section className="proof section"><p className="kicker">02 · PROOF, NOT PROMISES</p><div className="proof-grid">{[[PhoneCall,'Sales visibility','Built a call tracking system that connects mobile activity with management reporting.'],[School,'Clearer communication','Created a complete school website around the questions families actually ask.'],[ShieldCheck,'Secure foundations','Developed authentication and backend APIs with validation and protected access.'],[Gauge,'Performance by design','Improved product speed and usability through deliberate architecture and feedback.']].map(([I,t,p])=><article key={t}><I/><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section id="work" className="section work"><div className="section-head split"><div><p className="kicker">03 · SELECTED CASE STUDIES</p><h2>Work, unpacked.</h2></div><p>Not just what shipped — the problem, constraints, decisions, and lessons behind it.</p></div>{projects.slice(0,3).map((p,i)=><article className="project-feature" key={p.slug}><div className="project-visual"><Image src={p.image} alt={`${p.title} product interface mockup`} fill sizes="(max-width: 900px) 100vw, 55vw"/></div><div className="project-copy"><span className="project-index">0{i+1} / {p.category}</span><p className="kicker">{p.eyebrow}</p><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.tech.map(x=><span key={x}>{x}</span>)}</div><Link href={`/projects/${p.slug}`}>Read the case study <ArrowRight/></Link></div></article>)}<Link href="/projects" className="text-link">View all projects <ArrowRight/></Link></section>
<section id="thinking" className="section thinking"><div className="section-head"><p className="kicker">04 · THE OPERATING SYSTEM</p><h2>How I think about the work.</h2></div><div className="thinking-grid">{[['How I think','Begin with the friction, not the framework. The right technical decision follows a clear understanding of the people and constraints.'],['What I care about','Clarity, performance, clean code, scalable architecture, and products that remain useful after the demo.'],['How I work','Map the problem. Reduce uncertainty. Build the smallest truthful version. Test assumptions. Improve with evidence.'],['What it’s like to work with me','Clear communication, practical decisions, visible progress, and an honest conversation when tradeoffs appear.']].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section className="section skill-section"><div className="section-head split"><div><p className="kicker">05 · TOOLS IN CONTEXT</p><h2>Technology is a means.</h2></div><p>Each tool earns its place by solving a product or engineering problem.</p></div><div className="skill-grid">{skillGroups.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.text}</p><div className="tags">{s.items.map(x=><span key={x}>{x}</span>)}</div><small>{s.use}</small></article>)}</div></section>
<section id="explore" className="section explore"><div><p className="kicker">06 · CURRENTLY EXPLORING</p><h2>The edge of what I know.</h2><p>Active learning, applied through experiments rather than collected as labels.</p></div><div className="orbit">{['System design','AI integration','Native modules','Cloud deployment','Performance'].map((x,i)=><span key={x} style={{'--i':i}}>{x}</span>)}</div></section>
<section className="section mini-journey"><div className="section-head split"><div><p className="kicker">07 · THE JOURNEY</p><h2>Learning by building.</h2></div><Link href="/journey">Full timeline <ArrowRight/></Link></div>{journey.slice(-4).map(([n,t,p])=><div className="journey-row" key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></div>)}</section>
<section className="section workspace"><div className="section-head"><p className="kicker">08 · OPEN THE WORKSPACE</p><h2>A familiar way into the work.</h2></div><div className="folders">{['Selected Work','Experiments','Resume','About My Process','Contact'].map(x=><button onClick={()=>setFolder(x)} key={x}><Folder/><span>{x}</span><small>Open folder</small></button>)}</div>{folder&&<div className="modal" role="dialog" aria-modal="true"><div><button onClick={()=>setFolder(null)} aria-label="Close"><X/></button><p className="kicker">WORKSPACE / {folder}</p><h3>{folder}</h3><p>{folder==='Selected Work'?'Four product stories spanning web, mobile, and backend systems.':'A focused shortcut into this part of the portfolio.'}</p><Link className="button light" href={folder==='Contact'?'/contact':folder==='Resume'?'/resume':folder==='Selected Work'?'/projects':'/#thinking'}>Open <ArrowRight/></Link></div></div>}</section>
<section id="contact" className="cta"><p className="kicker">HAVE A PROBLEM WORTH SOLVING?</p><h2>Let’s discuss it.</h2><p>Tell me what is getting in the way. I’ll bring questions, clarity, and a practical route forward.</p><Link className="button dark" href="/contact">Start a conversation <ArrowRight/></Link></section></>}
